/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhiteLabelRouteImport } from './routes/_authenticated/white-label'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedTelaoRouteImport } from './routes/_authenticated/telao'
import { Route as AuthenticatedServicesTodoRouteImport } from './routes/_authenticated/services-todo'
import { Route as AuthenticatedSellersRouteImport } from './routes/_authenticated/sellers'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedProducersRouteImport } from './routes/_authenticated/producers'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPendingPaymentsRouteImport } from './routes/_authenticated/pending-payments'
import { Route as AuthenticatedPaymentLinkRouteImport } from './routes/_authenticated/payment-link'
import { Route as AuthenticatedPagarmeHistoryRouteImport } from './routes/_authenticated/pagarme-history'
import { Route as AuthenticatedOperacaoMetaRouteImport } from './routes/_authenticated/operacao-meta'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedChatOrganizadorRouteImport } from './routes/_authenticated/chat-organizador'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPastasArquivosIndexRouteImport } from './routes/_authenticated/pastas-arquivos.index'
import { Route as AuthenticatedOperacaoMetaIndexRouteImport } from './routes/_authenticated/operacao-meta.index'
import { Route as ApiPublicTrelloWebhookRouteImport } from './routes/api/public/trello-webhook'
import { Route as ApiPublicEvolutionWebhookRouteImport } from './routes/api/public/evolution-webhook'
import { Route as AuthenticatedPastasArquivosFolderIdRouteImport } from './routes/_authenticated/pastas-arquivos.$folderId'
import { Route as AuthenticatedOperacaoMetaVisaoGeralRouteImport } from './routes/_authenticated/operacao-meta.visao-geral'
import { Route as AuthenticatedOperacaoMetaTendenciasRouteImport } from './routes/_authenticated/operacao-meta.tendencias'
import { Route as AuthenticatedOperacaoMetaRelatoriosRouteImport } from './routes/_authenticated/operacao-meta.relatorios'
import { Route as AuthenticatedOperacaoMetaProdutoresRouteImport } from './routes/_authenticated/operacao-meta.produtores'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhiteLabelRoute = AuthenticatedWhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTelaoRoute = AuthenticatedTelaoRouteImport.update({
  id: '/telao',
  path: '/telao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesTodoRoute =
  AuthenticatedServicesTodoRouteImport.update({
    id: '/services-todo',
    path: '/services-todo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellersRoute = AuthenticatedSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducersRoute = AuthenticatedProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingPaymentsRoute =
  AuthenticatedPendingPaymentsRouteImport.update({
    id: '/pending-payments',
    path: '/pending-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentLinkRoute =
  AuthenticatedPaymentLinkRouteImport.update({
    id: '/payment-link',
    path: '/payment-link',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagarmeHistoryRoute =
  AuthenticatedPagarmeHistoryRouteImport.update({
    id: '/pagarme-history',
    path: '/pagarme-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoMetaRoute =
  AuthenticatedOperacaoMetaRouteImport.update({
    id: '/operacao-meta',
    path: '/operacao-meta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatOrganizadorRoute =
  AuthenticatedChatOrganizadorRouteImport.update({
    id: '/chat-organizador',
    path: '/chat-organizador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPastasArquivosIndexRoute =
  AuthenticatedPastasArquivosIndexRouteImport.update({
    id: '/pastas-arquivos/',
    path: '/pastas-arquivos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoMetaIndexRoute =
  AuthenticatedOperacaoMetaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperacaoMetaRoute,
  } as any)
const ApiPublicTrelloWebhookRoute = ApiPublicTrelloWebhookRouteImport.update({
  id: '/api/public/trello-webhook',
  path: '/api/public/trello-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvolutionWebhookRoute =
  ApiPublicEvolutionWebhookRouteImport.update({
    id: '/api/public/evolution-webhook',
    path: '/api/public/evolution-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPastasArquivosFolderIdRoute =
  AuthenticatedPastasArquivosFolderIdRouteImport.update({
    id: '/pastas-arquivos/$folderId',
    path: '/pastas-arquivos/$folderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoMetaVisaoGeralRoute =
  AuthenticatedOperacaoMetaVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AuthenticatedOperacaoMetaRoute,
  } as any)
const AuthenticatedOperacaoMetaTendenciasRoute =
  AuthenticatedOperacaoMetaTendenciasRouteImport.update({
    id: '/tendencias',
    path: '/tendencias',
    getParentRoute: () => AuthenticatedOperacaoMetaRoute,
  } as any)
const AuthenticatedOperacaoMetaRelatoriosRoute =
  AuthenticatedOperacaoMetaRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedOperacaoMetaRoute,
  } as any)
const AuthenticatedOperacaoMetaProdutoresRoute =
  AuthenticatedOperacaoMetaProdutoresRouteImport.update({
    id: '/produtores',
    path: '/produtores',
    getParentRoute: () => AuthenticatedOperacaoMetaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/chat-organizador': typeof AuthenticatedChatOrganizadorRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/master': typeof AuthenticatedMasterRoute
  '/operacao-meta': typeof AuthenticatedOperacaoMetaRouteWithChildren
  '/pagarme-history': typeof AuthenticatedPagarmeHistoryRoute
  '/payment-link': typeof AuthenticatedPaymentLinkRoute
  '/pending-payments': typeof AuthenticatedPendingPaymentsRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/producers': typeof AuthenticatedProducersRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/sellers': typeof AuthenticatedSellersRoute
  '/services-todo': typeof AuthenticatedServicesTodoRoute
  '/telao': typeof AuthenticatedTelaoRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/white-label': typeof AuthenticatedWhiteLabelRoute
  '/operacao-meta/produtores': typeof AuthenticatedOperacaoMetaProdutoresRoute
  '/operacao-meta/relatorios': typeof AuthenticatedOperacaoMetaRelatoriosRoute
  '/operacao-meta/tendencias': typeof AuthenticatedOperacaoMetaTendenciasRoute
  '/operacao-meta/visao-geral': typeof AuthenticatedOperacaoMetaVisaoGeralRoute
  '/pastas-arquivos/$folderId': typeof AuthenticatedPastasArquivosFolderIdRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/trello-webhook': typeof ApiPublicTrelloWebhookRoute
  '/operacao-meta/': typeof AuthenticatedOperacaoMetaIndexRoute
  '/pastas-arquivos/': typeof AuthenticatedPastasArquivosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/chat-organizador': typeof AuthenticatedChatOrganizadorRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/master': typeof AuthenticatedMasterRoute
  '/pagarme-history': typeof AuthenticatedPagarmeHistoryRoute
  '/payment-link': typeof AuthenticatedPaymentLinkRoute
  '/pending-payments': typeof AuthenticatedPendingPaymentsRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/producers': typeof AuthenticatedProducersRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/sellers': typeof AuthenticatedSellersRoute
  '/services-todo': typeof AuthenticatedServicesTodoRoute
  '/telao': typeof AuthenticatedTelaoRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/white-label': typeof AuthenticatedWhiteLabelRoute
  '/operacao-meta/produtores': typeof AuthenticatedOperacaoMetaProdutoresRoute
  '/operacao-meta/relatorios': typeof AuthenticatedOperacaoMetaRelatoriosRoute
  '/operacao-meta/tendencias': typeof AuthenticatedOperacaoMetaTendenciasRoute
  '/operacao-meta/visao-geral': typeof AuthenticatedOperacaoMetaVisaoGeralRoute
  '/pastas-arquivos/$folderId': typeof AuthenticatedPastasArquivosFolderIdRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/trello-webhook': typeof ApiPublicTrelloWebhookRoute
  '/operacao-meta': typeof AuthenticatedOperacaoMetaIndexRoute
  '/pastas-arquivos': typeof AuthenticatedPastasArquivosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/chat-organizador': typeof AuthenticatedChatOrganizadorRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/operacao-meta': typeof AuthenticatedOperacaoMetaRouteWithChildren
  '/_authenticated/pagarme-history': typeof AuthenticatedPagarmeHistoryRoute
  '/_authenticated/payment-link': typeof AuthenticatedPaymentLinkRoute
  '/_authenticated/pending-payments': typeof AuthenticatedPendingPaymentsRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/producers': typeof AuthenticatedProducersRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/sellers': typeof AuthenticatedSellersRoute
  '/_authenticated/services-todo': typeof AuthenticatedServicesTodoRoute
  '/_authenticated/telao': typeof AuthenticatedTelaoRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/white-label': typeof AuthenticatedWhiteLabelRoute
  '/_authenticated/operacao-meta/produtores': typeof AuthenticatedOperacaoMetaProdutoresRoute
  '/_authenticated/operacao-meta/relatorios': typeof AuthenticatedOperacaoMetaRelatoriosRoute
  '/_authenticated/operacao-meta/tendencias': typeof AuthenticatedOperacaoMetaTendenciasRoute
  '/_authenticated/operacao-meta/visao-geral': typeof AuthenticatedOperacaoMetaVisaoGeralRoute
  '/_authenticated/pastas-arquivos/$folderId': typeof AuthenticatedPastasArquivosFolderIdRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/trello-webhook': typeof ApiPublicTrelloWebhookRoute
  '/_authenticated/operacao-meta/': typeof AuthenticatedOperacaoMetaIndexRoute
  '/_authenticated/pastas-arquivos/': typeof AuthenticatedPastasArquivosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/auditoria'
    | '/backup'
    | '/chat-organizador'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/invoices'
    | '/kanban'
    | '/master'
    | '/operacao-meta'
    | '/pagarme-history'
    | '/payment-link'
    | '/pending-payments'
    | '/planos'
    | '/producers'
    | '/sales'
    | '/sellers'
    | '/services-todo'
    | '/telao'
    | '/whatsapp'
    | '/white-label'
    | '/operacao-meta/produtores'
    | '/operacao-meta/relatorios'
    | '/operacao-meta/tendencias'
    | '/operacao-meta/visao-geral'
    | '/pastas-arquivos/$folderId'
    | '/api/public/evolution-webhook'
    | '/api/public/trello-webhook'
    | '/operacao-meta/'
    | '/pastas-arquivos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/auditoria'
    | '/backup'
    | '/chat-organizador'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/invoices'
    | '/kanban'
    | '/master'
    | '/pagarme-history'
    | '/payment-link'
    | '/pending-payments'
    | '/planos'
    | '/producers'
    | '/sales'
    | '/sellers'
    | '/services-todo'
    | '/telao'
    | '/whatsapp'
    | '/white-label'
    | '/operacao-meta/produtores'
    | '/operacao-meta/relatorios'
    | '/operacao-meta/tendencias'
    | '/operacao-meta/visao-geral'
    | '/pastas-arquivos/$folderId'
    | '/api/public/evolution-webhook'
    | '/api/public/trello-webhook'
    | '/operacao-meta'
    | '/pastas-arquivos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/auditoria'
    | '/_authenticated/backup'
    | '/_authenticated/chat-organizador'
    | '/_authenticated/commissions'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/invoices'
    | '/_authenticated/kanban'
    | '/_authenticated/master'
    | '/_authenticated/operacao-meta'
    | '/_authenticated/pagarme-history'
    | '/_authenticated/payment-link'
    | '/_authenticated/pending-payments'
    | '/_authenticated/planos'
    | '/_authenticated/producers'
    | '/_authenticated/sales'
    | '/_authenticated/sellers'
    | '/_authenticated/services-todo'
    | '/_authenticated/telao'
    | '/_authenticated/whatsapp'
    | '/_authenticated/white-label'
    | '/_authenticated/operacao-meta/produtores'
    | '/_authenticated/operacao-meta/relatorios'
    | '/_authenticated/operacao-meta/tendencias'
    | '/_authenticated/operacao-meta/visao-geral'
    | '/_authenticated/pastas-arquivos/$folderId'
    | '/api/public/evolution-webhook'
    | '/api/public/trello-webhook'
    | '/_authenticated/operacao-meta/'
    | '/_authenticated/pastas-arquivos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicEvolutionWebhookRoute: typeof ApiPublicEvolutionWebhookRoute
  ApiPublicTrelloWebhookRoute: typeof ApiPublicTrelloWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/white-label': {
      id: '/_authenticated/white-label'
      path: '/white-label'
      fullPath: '/white-label'
      preLoaderRoute: typeof AuthenticatedWhiteLabelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/telao': {
      id: '/_authenticated/telao'
      path: '/telao'
      fullPath: '/telao'
      preLoaderRoute: typeof AuthenticatedTelaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services-todo': {
      id: '/_authenticated/services-todo'
      path: '/services-todo'
      fullPath: '/services-todo'
      preLoaderRoute: typeof AuthenticatedServicesTodoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sellers': {
      id: '/_authenticated/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof AuthenticatedSellersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producers': {
      id: '/_authenticated/producers'
      path: '/producers'
      fullPath: '/producers'
      preLoaderRoute: typeof AuthenticatedProducersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending-payments': {
      id: '/_authenticated/pending-payments'
      path: '/pending-payments'
      fullPath: '/pending-payments'
      preLoaderRoute: typeof AuthenticatedPendingPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-link': {
      id: '/_authenticated/payment-link'
      path: '/payment-link'
      fullPath: '/payment-link'
      preLoaderRoute: typeof AuthenticatedPaymentLinkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagarme-history': {
      id: '/_authenticated/pagarme-history'
      path: '/pagarme-history'
      fullPath: '/pagarme-history'
      preLoaderRoute: typeof AuthenticatedPagarmeHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao-meta': {
      id: '/_authenticated/operacao-meta'
      path: '/operacao-meta'
      fullPath: '/operacao-meta'
      preLoaderRoute: typeof AuthenticatedOperacaoMetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat-organizador': {
      id: '/_authenticated/chat-organizador'
      path: '/chat-organizador'
      fullPath: '/chat-organizador'
      preLoaderRoute: typeof AuthenticatedChatOrganizadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pastas-arquivos/': {
      id: '/_authenticated/pastas-arquivos/'
      path: '/pastas-arquivos'
      fullPath: '/pastas-arquivos/'
      preLoaderRoute: typeof AuthenticatedPastasArquivosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao-meta/': {
      id: '/_authenticated/operacao-meta/'
      path: '/'
      fullPath: '/operacao-meta/'
      preLoaderRoute: typeof AuthenticatedOperacaoMetaIndexRouteImport
      parentRoute: typeof AuthenticatedOperacaoMetaRoute
    }
    '/api/public/trello-webhook': {
      id: '/api/public/trello-webhook'
      path: '/api/public/trello-webhook'
      fullPath: '/api/public/trello-webhook'
      preLoaderRoute: typeof ApiPublicTrelloWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution-webhook': {
      id: '/api/public/evolution-webhook'
      path: '/api/public/evolution-webhook'
      fullPath: '/api/public/evolution-webhook'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pastas-arquivos/$folderId': {
      id: '/_authenticated/pastas-arquivos/$folderId'
      path: '/pastas-arquivos/$folderId'
      fullPath: '/pastas-arquivos/$folderId'
      preLoaderRoute: typeof AuthenticatedPastasArquivosFolderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao-meta/visao-geral': {
      id: '/_authenticated/operacao-meta/visao-geral'
      path: '/visao-geral'
      fullPath: '/operacao-meta/visao-geral'
      preLoaderRoute: typeof AuthenticatedOperacaoMetaVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedOperacaoMetaRoute
    }
    '/_authenticated/operacao-meta/tendencias': {
      id: '/_authenticated/operacao-meta/tendencias'
      path: '/tendencias'
      fullPath: '/operacao-meta/tendencias'
      preLoaderRoute: typeof AuthenticatedOperacaoMetaTendenciasRouteImport
      parentRoute: typeof AuthenticatedOperacaoMetaRoute
    }
    '/_authenticated/operacao-meta/relatorios': {
      id: '/_authenticated/operacao-meta/relatorios'
      path: '/relatorios'
      fullPath: '/operacao-meta/relatorios'
      preLoaderRoute: typeof AuthenticatedOperacaoMetaRelatoriosRouteImport
      parentRoute: typeof AuthenticatedOperacaoMetaRoute
    }
    '/_authenticated/operacao-meta/produtores': {
      id: '/_authenticated/operacao-meta/produtores'
      path: '/produtores'
      fullPath: '/operacao-meta/produtores'
      preLoaderRoute: typeof AuthenticatedOperacaoMetaProdutoresRouteImport
      parentRoute: typeof AuthenticatedOperacaoMetaRoute
    }
  }
}

interface AuthenticatedOperacaoMetaRouteChildren {
  AuthenticatedOperacaoMetaProdutoresRoute: typeof AuthenticatedOperacaoMetaProdutoresRoute
  AuthenticatedOperacaoMetaRelatoriosRoute: typeof AuthenticatedOperacaoMetaRelatoriosRoute
  AuthenticatedOperacaoMetaTendenciasRoute: typeof AuthenticatedOperacaoMetaTendenciasRoute
  AuthenticatedOperacaoMetaVisaoGeralRoute: typeof AuthenticatedOperacaoMetaVisaoGeralRoute
  AuthenticatedOperacaoMetaIndexRoute: typeof AuthenticatedOperacaoMetaIndexRoute
}

const AuthenticatedOperacaoMetaRouteChildren: AuthenticatedOperacaoMetaRouteChildren =
  {
    AuthenticatedOperacaoMetaProdutoresRoute:
      AuthenticatedOperacaoMetaProdutoresRoute,
    AuthenticatedOperacaoMetaRelatoriosRoute:
      AuthenticatedOperacaoMetaRelatoriosRoute,
    AuthenticatedOperacaoMetaTendenciasRoute:
      AuthenticatedOperacaoMetaTendenciasRoute,
    AuthenticatedOperacaoMetaVisaoGeralRoute:
      AuthenticatedOperacaoMetaVisaoGeralRoute,
    AuthenticatedOperacaoMetaIndexRoute: AuthenticatedOperacaoMetaIndexRoute,
  }

const AuthenticatedOperacaoMetaRouteWithChildren =
  AuthenticatedOperacaoMetaRoute._addFileChildren(
    AuthenticatedOperacaoMetaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedChatOrganizadorRoute: typeof AuthenticatedChatOrganizadorRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedOperacaoMetaRoute: typeof AuthenticatedOperacaoMetaRouteWithChildren
  AuthenticatedPagarmeHistoryRoute: typeof AuthenticatedPagarmeHistoryRoute
  AuthenticatedPaymentLinkRoute: typeof AuthenticatedPaymentLinkRoute
  AuthenticatedPendingPaymentsRoute: typeof AuthenticatedPendingPaymentsRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedProducersRoute: typeof AuthenticatedProducersRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSellersRoute: typeof AuthenticatedSellersRoute
  AuthenticatedServicesTodoRoute: typeof AuthenticatedServicesTodoRoute
  AuthenticatedTelaoRoute: typeof AuthenticatedTelaoRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedWhiteLabelRoute: typeof AuthenticatedWhiteLabelRoute
  AuthenticatedPastasArquivosFolderIdRoute: typeof AuthenticatedPastasArquivosFolderIdRoute
  AuthenticatedPastasArquivosIndexRoute: typeof AuthenticatedPastasArquivosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedChatOrganizadorRoute: AuthenticatedChatOrganizadorRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedOperacaoMetaRoute: AuthenticatedOperacaoMetaRouteWithChildren,
  AuthenticatedPagarmeHistoryRoute: AuthenticatedPagarmeHistoryRoute,
  AuthenticatedPaymentLinkRoute: AuthenticatedPaymentLinkRoute,
  AuthenticatedPendingPaymentsRoute: AuthenticatedPendingPaymentsRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedProducersRoute: AuthenticatedProducersRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSellersRoute: AuthenticatedSellersRoute,
  AuthenticatedServicesTodoRoute: AuthenticatedServicesTodoRoute,
  AuthenticatedTelaoRoute: AuthenticatedTelaoRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedWhiteLabelRoute: AuthenticatedWhiteLabelRoute,
  AuthenticatedPastasArquivosFolderIdRoute:
    AuthenticatedPastasArquivosFolderIdRoute,
  AuthenticatedPastasArquivosIndexRoute: AuthenticatedPastasArquivosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicEvolutionWebhookRoute: ApiPublicEvolutionWebhookRoute,
  ApiPublicTrelloWebhookRoute: ApiPublicTrelloWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
