
ALTER TABLE public.agents
  ADD COLUMN IF NOT EXISTS avatar_url text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS language text DEFAULT 'pt-BR',
  ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'America/Sao_Paulo',
  ADD COLUMN IF NOT EXISTS model text,
  ADD COLUMN IF NOT EXISTS max_tokens integer DEFAULT 2048,
  ADD COLUMN IF NOT EXISTS top_p numeric DEFAULT 1,
  ADD COLUMN IF NOT EXISTS top_k integer,
  ADD COLUMN IF NOT EXISTS seed integer,
  ADD COLUMN IF NOT EXISTS frequency_penalty numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS presence_penalty numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stop_sequences text[],
  ADD COLUMN IF NOT EXISTS streaming boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS thinking_mode boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS tools jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS memory jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS knowledge jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS security jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS integrations jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS appearance jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS initial_message text,
  ADD COLUMN IF NOT EXISTS primary_color text DEFAULT '#22c55e',
  ADD COLUMN IF NOT EXISTS secondary_color text DEFAULT '#000000';
